services:
  mysql:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customer
      MYSQL_USER: codeenterprise
      MYSQL_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
